name: Build ZIPs

on:
  push:
    branches:
      - main

jobs:
  build-zip:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Create zip folder if it doesn't exist
      - name: Create zip folder
        run: mkdir -p zip

      # 3. Zip each top-level folder, excluding the zip folder itself
      - name: Zip top-level folders
        run: |
          mkdir -p zip
          for dir in */ ; do
            folder_name=$(basename "$dir")
            if [ "$folder_name" != "zip" ]; then
              (cd "$folder_name" && zip -r "../zip/${folder_name}.zip" .)
            fi
          done


      # 4. Upload each zip separately
      - name: Upload ZIPs individually
        uses: actions/upload-artifact@v4
        with:
          name: java-zip
          path: zip/java.zip

      - uses: actions/upload-artifact@v4
        with:
          name: bedrock-zip
          path: zip/bedrock.zip
